version: '3.3'

services:
  #backend api
  # api:
  #   container_name: api_container
  #   build: ./ChattingCore
  #   working_dir: /usr/src/api_app
  #   # restart: always
  #   ports:
  #     - "3001:${PORT}"
  #   command: npm start
  #   volumes: 
  #     - .:/usr/src/api_app
  #     # - /usr/src/api_app/node_modules/bcrypt/
  #     # - /usr/src/api_app/node_modules/express-fileupload/
  #   depends_on:
  #     - postgres
  #     - redis
  #   environment:
  #     JSONWEBTOKENSECRET: ${JSONWEBTOKENSECRET}
  #     PORT: ${API1_PORT}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_HOST: ${POSTGRES_HOST}
  #     POSTGRES_URL: ${POSTGRES_URL}
  #     REDIS_URL: ${REDIS_URL}
  
  # # monguito:
  # mongo:
  #   # container_name: mongo_container
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  #   volumes:
  #     - mongo-data:/data/db
  #     # mysql -> /var/lib/mysql
  #     # postgres -> /var/lib/postgresql/data
  
  redis:
    image: redis
    # container_name: redis_container
    # restart: always
    ports:
      - "6379:6379"

# volumes:
#   mongo-data: