version: '3.3'

services:
  #backend api
  # api:
  #   container_name: api_container
  #   build: ./ChattingCore
  #   working_dir: /usr/src/api_app
  #   # restart: always
  #   ports:
  #     - "3001:${PORT}"
  #   command: npm start
  #   volumes: 
  #     - .:/usr/src/api_app
  #     # - /usr/src/api_app/node_modules/bcrypt/
  #     # - /usr/src/api_app/node_modules/express-fileupload/
  #   depends_on:
  #     - postgres
  #     - redis
  #   environment:
  #     JSONWEBTOKENSECRET: ${JSONWEBTOKENSECRET}
  #     PORT: ${API1_PORT}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_HOST: ${POSTGRES_HOST}
  #     POSTGRES_URL: ${POSTGRES_URL}
  #     REDIS_URL: ${REDIS_URL}


  postgres:
    container_name: postgres_container
    image: postgres
    # build: ./postgres_docker
    ports:
      - "5432:5432"
    # restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # mysql -> /var/lib/mysql

volumes:
  postgres-data: